// data/dummy_data.dart
import 'package:test_case_ayo/model/leaderboard_model.dart';

class DummyData {
  // Data Leaderboard untuk Tunggal (Nama Orang)
  static List<LeaderboardItem> get tunggalLeaderboard => [
    // BADMINTON - SURABAYA
    LeaderboardItem(
      id: '1',
      name: 'Gilang Kencana',
      username: '@gilangkencana',
      points: 250,
      rank: 1,
      location: 'Surabaya',
      type: 'Tunggal',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_gilang.png",
    ),
    LeaderboardItem(
      id: '2',
      name: 'Kevin Halim',
      username: '@kevinhalim',
      points: 245,
      rank: 2,
      location: 'Surabaya',
      type: 'Tunggal',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_kevin.png",
    ),
    LeaderboardItem(
      id: '3',
      name: 'Narpati Lukita',
      username: '@narpatilukita',
      points: 240,
      rank: 3,
      location: 'Surabaya',
      type: 'Tunggal',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_narpatika.png",
    ),
    LeaderboardItem(
      id: '4',
      name: 'Budiman Mustofa',
      username: '@budimanmustofa',
      points: 235,
      rank: 4,
      location: 'Surabaya',
      type: 'Tunggal',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_budiman.png",
    ),
    LeaderboardItem(
      id: '5',
      name: 'Leo Adriansyah',
      username: '@leo.adrian',
      points: 230,
      rank: 5,
      location: 'Surabaya',
      type: 'Tunggal',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_leo.png",
    ),
    LeaderboardItem(
      id: '6',
      name: 'Kemal Halim',
      username: '@halimkemal',
      points: 225,
      rank: 6,
      location: 'Surabaya',
      type: 'Tunggal',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_kemal.png",
    ),
    LeaderboardItem(
      id: '7',
      name: 'Ravi Kusumo',
      username: '@ravikusumo',
      points: 220,
      rank: 7,
      location: 'Surabaya',
      type: 'Tunggal',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '8',
      name: 'Ahmad Fauzi',
      username: '@ahmadfauzi',
      points: 215,
      rank: 8,
      location: 'Surabaya',
      type: 'Tunggal',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '9',
      name: 'Budi Santoso',
      username: '@budisantoso',
      points: 210,
      rank: 9,
      location: 'Surabaya',
      type: 'Tunggal',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '10',
      name: 'Cahya Pratama',
      username: '@cahyapratama',
      points: 205,
      rank: 10,
      location: 'Surabaya',
      type: 'Tunggal',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),

    // BADMINTON - JAKARTA
    LeaderboardItem(
      id: '11',
      name: 'Dian Sastro',
      username: '@diansastro',
      points: 250,
      rank: 1,
      location: 'Jakarta',
      type: 'Tunggal',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '12',
      name: 'Eko Prasetyo',
      username: '@ekoprasetyo',
      points: 245,
      rank: 2,
      location: 'Jakarta',
      type: 'Tunggal',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '13',
      name: 'Fajar Nugroho',
      username: '@fajarnugroho',
      points: 240,
      rank: 3,
      location: 'Jakarta',
      type: 'Tunggal',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '14',
      name: 'Gita Wulandari',
      username: '@gitawulandari',
      points: 235,
      rank: 4,
      location: 'Jakarta',
      type: 'Tunggal',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '15',
      name: 'Hendra Setiawan',
      username: '@hendrasetiawan',
      points: 230,
      rank: 5,
      location: 'Jakarta',
      type: 'Tunggal',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '16',
      name: 'Indra Kurniawan',
      username: '@indrakurniawan',
      points: 225,
      rank: 6,
      location: 'Jakarta',
      type: 'Tunggal',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '17',
      name: 'Joko Widodo',
      username: '@jokowidodo',
      points: 220,
      rank: 7,
      location: 'Jakarta',
      type: 'Tunggal',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '18',
      name: 'Kartika Sari',
      username: '@kartikasarī',
      points: 215,
      rank: 8,
      location: 'Jakarta',
      type: 'Tunggal',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '19',
      name: 'Lukman Hakim',
      username: '@lukmanhakim',
      points: 210,
      rank: 9,
      location: 'Jakarta',
      type: 'Tunggal',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '20',
      name: 'Maya Fitriani',
      username: '@mayafitriani',
      points: 205,
      rank: 10,
      location: 'Jakarta',
      type: 'Tunggal',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),

    // BADMINTON - BANDUNG
    LeaderboardItem(
      id: '21',
      name: 'Nina Astuti',
      username: '@ninaastuti',
      points: 250,
      rank: 1,
      location: 'Bandung',
      type: 'Tunggal',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '22',
      name: 'Oki Setiawan',
      username: '@okisetiawan',
      points: 245,
      rank: 2,
      location: 'Bandung',
      type: 'Tunggal',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '23',
      name: 'Putri Anggraini',
      username: '@putrianggraini',
      points: 240,
      rank: 3,
      location: 'Bandung',
      type: 'Tunggal',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '24',
      name: 'Rizky Pratama',
      username: '@rizkypratama',
      points: 235,
      rank: 4,
      location: 'Bandung',
      type: 'Tunggal',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '25',
      name: 'Sari Indah',
      username: '@sariindah',
      points: 230,
      rank: 5,
      location: 'Bandung',
      type: 'Tunggal',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '26',
      name: 'Tono Wijaya',
      username: '@tonowijaya',
      points: 225,
      rank: 6,
      location: 'Bandung',
      type: 'Tunggal',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '27',
      name: 'Umi Kulsum',
      username: '@umikulsum',
      points: 220,
      rank: 7,
      location: 'Bandung',
      type: 'Tunggal',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '28',
      name: 'Vino Bastian',
      username: '@vinobastian',
      points: 215,
      rank: 8,
      location: 'Bandung',
      type: 'Tunggal',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '29',
      name: 'Wulan Sari',
      username: '@wulansari',
      points: 210,
      rank: 9,
      location: 'Bandung',
      type: 'Tunggal',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '30',
      name: 'Xavier Tan',
      username: '@xaviertan',
      points: 205,
      rank: 10,
      location: 'Bandung',
      type: 'Tunggal',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),

    // TENIS MEJA - SURABAYA
    LeaderboardItem(
      id: '31',
      name: 'Yudi Hartono',
      username: '@yudihartono',
      points: 250,
      rank: 1,
      location: 'Surabaya',
      type: 'Tunggal',
      category: 'Tenis Meja',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '32',
      name: 'Zahra Fitri',
      username: '@zahrafitri',
      points: 245,
      rank: 2,
      location: 'Surabaya',
      type: 'Tunggal',
      category: 'Tenis Meja',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '33',
      name: 'Arya Putra',
      username: '@aryaputra',
      points: 240,
      rank: 3,
      location: 'Surabaya',
      type: 'Tunggal',
      category: 'Tenis Meja',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '34',
      name: 'Bella Nurul',
      username: '@bellanurul',
      points: 235,
      rank: 4,
      location: 'Surabaya',
      type: 'Tunggal',
      category: 'Tenis Meja',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '35',
      name: 'Candra Wijaya',
      username: '@candrawijaya',
      points: 230,
      rank: 5,
      location: 'Surabaya',
      type: 'Tunggal',
      category: 'Tenis Meja',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '36',
      name: 'Dewi Lestari',
      username: '@dewilestari',
      points: 225,
      rank: 6,
      location: 'Surabaya',
      type: 'Tunggal',
      category: 'Tenis Meja',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '37',
      name: 'Eko Yulianto',
      username: '@ekoyulianto',
      points: 220,
      rank: 7,
      location: 'Surabaya',
      type: 'Tunggal',
      category: 'Tenis Meja',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '38',
      name: 'Fitri Handayani',
      username: '@fitrihandayani',
      points: 215,
      rank: 8,
      location: 'Surabaya',
      type: 'Tunggal',
      category: 'Tenis Meja',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '39',
      name: 'Gunawan Susilo',
      username: '@gunawansusilo',
      points: 210,
      rank: 9,
      location: 'Surabaya',
      type: 'Tunggal',
      category: 'Tenis Meja',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '40',
      name: 'Hana Wijaya',
      username: '@hanawijaya',
      points: 205,
      rank: 10,
      location: 'Surabaya',
      type: 'Tunggal',
      category: 'Tenis Meja',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),

    // TENIS MEJA - JAKARTA
    LeaderboardItem(
      id: '41',
      name: 'Ivan Gunawan',
      username: '@ivangunawan',
      points: 250,
      rank: 1,
      location: 'Jakarta',
      type: 'Tunggal',
      category: 'Tenis Meja',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '42',
      name: 'Jasmine Putri',
      username: '@jasmineputri',
      points: 245,
      rank: 2,
      location: 'Jakarta',
      type: 'Tunggal',
      category: 'Tenis Meja',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '43',
      name: 'Kevin Anggoro',
      username: '@kevinanggoro',
      points: 240,
      rank: 3,
      location: 'Jakarta',
      type: 'Tunggal',
      category: 'Tenis Meja',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '44',
      name: 'Lina Marlina',
      username: '@linamarlina',
      points: 235,
      rank: 4,
      location: 'Jakarta',
      type: 'Tunggal',
      category: 'Tenis Meja',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '45',
      name: 'Mario Kusumo',
      username: '@mariokusumo',
      points: 230,
      rank: 5,
      location: 'Jakarta',
      type: 'Tunggal',
      category: 'Tenis Meja',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '46',
      name: 'Nadia Fitri',
      username: '@nadiafitri',
      points: 225,
      rank: 6,
      location: 'Jakarta',
      type: 'Tunggal',
      category: 'Tenis Meja',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '47',
      name: 'Oscar Wijaya',
      username: '@oscarwijaya',
      points: 220,
      rank: 7,
      location: 'Jakarta',
      type: 'Tunggal',
      category: 'Tenis Meja',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '48',
      name: 'Putra Aditya',
      username: '@putraaditya',
      points: 215,
      rank: 8,
      location: 'Jakarta',
      type: 'Tunggal',
      category: 'Tenis Meja',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '49',
      name: 'Queen Elizabeth',
      username: '@queenelizabeth',
      points: 210,
      rank: 9,
      location: 'Jakarta',
      type: 'Tunggal',
      category: 'Tenis Meja',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '50',
      name: 'Randy Orton',
      username: '@randyorton',
      points: 205,
      rank: 10,
      location: 'Jakarta',
      type: 'Tunggal',
      category: 'Tenis Meja',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),

    // TENIS MEJA - BANDUNG
    LeaderboardItem(
      id: '51',
      name: 'Siti Nurhaliza',
      username: '@sitinurhaliza',
      points: 250,
      rank: 1,
      location: 'Bandung',
      type: 'Tunggal',
      category: 'Tenis Meja',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '52',
      name: 'Teguh Pratama',
      username: '@teguhpratama',
      points: 245,
      rank: 2,
      location: 'Bandung',
      type: 'Tunggal',
      category: 'Tenis Meja',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '53',
      name: 'Umi Salamah',
      username: '@umisalamah',
      points: 240,
      rank: 3,
      location: 'Bandung',
      type: 'Tunggal',
      category: 'Tenis Meja',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '54',
      name: 'Vicky Prasetyo',
      username: '@vickyprasetyo',
      points: 235,
      rank: 4,
      location: 'Bandung',
      type: 'Tunggal',
      category: 'Tenis Meja',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '55',
      name: 'Wahyu Adi',
      username: '@wahyuadi',
      points: 230,
      rank: 5,
      location: 'Bandung',
      type: 'Tunggal',
      category: 'Tenis Meja',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '56',
      name: 'Xena Princess',
      username: '@xenaprincess',
      points: 225,
      rank: 6,
      location: 'Bandung',
      type: 'Tunggal',
      category: 'Tenis Meja',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '57',
      name: 'Yoga Pratama',
      username: '@yogapratama',
      points: 220,
      rank: 7,
      location: 'Bandung',
      type: 'Tunggal',
      category: 'Tenis Meja',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '58',
      name: 'Zulkifli Hasan',
      username: '@zulkiflihasan',
      points: 215,
      rank: 8,
      location: 'Bandung',
      type: 'Tunggal',
      category: 'Tenis Meja',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '59',
      name: 'Ahmad Dhani',
      username: '@ahmaddhani',
      points: 210,
      rank: 9,
      location: 'Bandung',
      type: 'Tunggal',
      category: 'Tenis Meja',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '60',
      name: 'Bambang Pamungkas',
      username: '@bambangpamungkas',
      points: 205,
      rank: 10,
      location: 'Bandung',
      type: 'Tunggal',
      category: 'Tenis Meja',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),

    // TENIS - SURABAYA
    LeaderboardItem(
      id: '61',
      name: 'Cristiano Ronaldo',
      username: '@cristiano',
      points: 250,
      rank: 1,
      location: 'Surabaya',
      type: 'Tunggal',
      category: 'Tenis',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '62',
      name: 'David Beckham',
      username: '@davidbeckham',
      points: 245,
      rank: 2,
      location: 'Surabaya',
      type: 'Tunggal',
      category: 'Tenis',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '63',
      name: 'Eden Hazard',
      username: '@edenhazard',
      points: 240,
      rank: 3,
      location: 'Surabaya',
      type: 'Tunggal',
      category: 'Tenis',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '64',
      name: 'Frank Lampard',
      username: '@franklampard',
      points: 235,
      rank: 4,
      location: 'Surabaya',
      type: 'Tunggal',
      category: 'Tenis',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '65',
      name: 'Gareth Bale',
      username: '@garethbale',
      points: 230,
      rank: 5,
      location: 'Surabaya',
      type: 'Tunggal',
      category: 'Tenis',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '66',
      name: 'Harry Kane',
      username: '@harrykane',
      points: 225,
      rank: 6,
      location: 'Surabaya',
      type: 'Tunggal',
      category: 'Tenis',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '67',
      name: 'Iker Casillas',
      username: '@ikercasillas',
      points: 220,
      rank: 7,
      location: 'Surabaya',
      type: 'Tunggal',
      category: 'Tenis',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '68',
      name: 'John Terry',
      username: '@johnterry',
      points: 215,
      rank: 8,
      location: 'Surabaya',
      type: 'Tunggal',
      category: 'Tenis',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '69',
      name: 'Kylian Mbappé',
      username: '@kylianmbappe',
      points: 210,
      rank: 9,
      location: 'Surabaya',
      type: 'Tunggal',
      category: 'Tenis',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),
    LeaderboardItem(
      id: '70',
      name: 'Lionel Messi',
      username: '@lionelmessi',
      points: 205,
      rank: 10,
      location: 'Surabaya',
      type: 'Tunggal',
      category: 'Tenis',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_ravi.png",
    ),

    // User berada di peringkat 456 untuk Badminton Surabaya
    LeaderboardItem(
      id: '71',
      name: 'Budiman Tanuwijaya',
      username: '@budimantanu',
      points: 105,
      rank: 456,
      location: 'Surabaya',
      type: 'Tunggal',
      category: 'Badminton',
      season: 'Current Season',
      isUser: true,
      imageUrl: "assets/icons/ic_budiman.png",
    ),
  ];

  // Data untuk Ganda (Pasangan Orang)
  static List<LeaderboardItem> get gandaLeaderboard => [
    LeaderboardItem(
      id: '72',
      name: 'Gilang / Ravi',
      username: '@gilangkencana / @ravikusumo',
      points: 280,
      rank: 1,
      location: 'Surabaya',
      type: 'Ganda',
      category: 'Tenis Meja',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_gilang.png",
      imageUrl2: "assets/icons/ic_ravi.png",
      participants: ['Gilang Kencana', 'Ravi Kusumo'],
    ),
    LeaderboardItem(
      id: '73',
      name: 'Kevin / Kemal',
      username: '@kevinhalim / @halimkemal',
      points: 275,
      rank: 2,
      location: 'Surabaya',
      type: 'Ganda',
      category: 'Tenis Meja',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_kevin.png",
      imageUrl2: "assets/icons/ic_kemal.png",
      participants: ['Kevin Halim', 'Kemal Halim'],
    ),
    LeaderboardItem(
      id: '74',
      name: 'Narpati / Leo',
      username: '@narpatilukita / @leo.adrian',
      points: 270,
      rank: 3,
      location: 'Surabaya',
      type: 'Ganda',
      category: 'Tenis Meja',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_narpatika.png",
      imageUrl2: "assets/icons/ic_leo.png",
      participants: ['Narpati Lukita', 'Leo Adriansyah'],
    ),
    LeaderboardItem(
      id: '75',
      name: 'Budiman / Alfarizi',
      username: '@budimantanu / @alfarizi',
      points: 265,
      rank: 4,
      location: 'Surabaya',
      type: 'Ganda',
      category: 'Tenis Meja',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_budiman.png",
      imageUrl2: "assets/icons/ic_leo.png",
      participants: ['Budiman Tanuwijaya', 'Alfarizi'],
      isUser: true,
    ),
    LeaderboardItem(
      id: '76',
      name: 'Gilang / Ravi',
      username: '@gilangkencana / @ravikusumo',
      points: 260,
      rank: 1,
      location: 'Surabaya',
      type: 'Ganda',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_gilang.png",
      imageUrl2: "assets/icons/ic_ravi.png",
      participants: ['Gilang Kencana', 'Ravi Kusumo'],
    ),
    LeaderboardItem(
      id: '77',
      name: 'Kevin / Kemal',
      username: '@kevinhalim / @halimkemal',
      points: 255,
      rank: 2,
      location: 'Surabaya',
      type: 'Ganda',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_kevin.png",
      imageUrl2: "assets/icons/ic_kemal.png",
      participants: ['Kevin Halim', 'Kemal Halim'],
    ),
    LeaderboardItem(
      id: '78',
      name: 'Narpati / Leo',
      username: '@narpatilukita / @leo.adrian',
      points: 250,
      rank: 3,
      location: 'Surabaya',
      type: 'Ganda',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_narpatika.png",
      imageUrl2: "assets/icons/ic_leo.png",
      participants: ['Narpati Lukita', 'Leo Adriansyah'],
    ),
    LeaderboardItem(
      id: '79',
      name: 'Budiman / Alfarizi',
      username: '@budimantanu / @alfarizi',
      points: 245,
      rank: 4,
      location: 'Surabaya',
      type: 'Ganda',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_budiman.png",
      imageUrl2: "assets/icons/ic_leo.png",
      participants: ['Budiman Tanuwijaya', 'Alfarizi'],
      isUser: true,
    ),
  ];

  // Data untuk Komunitas (Tetap ada tapi opsional)
  static List<LeaderboardItem> get komunitasLeaderboard => [
    LeaderboardItem(
      id: '80',
      name: 'Badminton Club Surabaya',
      points: 300,
      rank: 1,
      location: 'Surabaya',
      username: 'Surabaya',
      type: 'komunitas',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_purple.png",
    ),
    LeaderboardItem(
      id: '81',
      name: 'Teal Badminton Surabaya',
      points: 260,
      rank: 2,
      location: 'Surabaya',
      username: 'Surabaya',
      type: 'komunitas',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_teal.png",
    ),
    LeaderboardItem(
      id: '82',
      name: 'Pinky Club',
      points: 200,
      rank: 3,
      location: 'Surabaya',
      username: 'Surabaya',
      type: 'komunitas',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_pinky.png",
    ),
    LeaderboardItem(
      id: '83',
      name: 'Blue House',
      points: 200,
      rank: 4,
      location: 'Surabaya',
      username: 'Surabaya',
      type: 'komunitas',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_bluehouse.png",
    ),
    LeaderboardItem(
      id: '84',
      name: 'Blue House Jakarta',
      points: 295,
      rank: 1,
      location: 'Jakarta',
      username: 'Jakarta',
      type: 'komunitas',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_bluehouse.png",
    ),
    LeaderboardItem(
      id: '85',
      name: 'Kawan Ayo',
      points: 255,
      rank: 2,
      location: 'Jakarta',
      username: 'Jakarta',
      type: 'komunitas',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_kawan_ayo.png",
    ),
    LeaderboardItem(
      id: '86',
      name: 'Grizzly',
      points: 205,
      rank: 3,
      location: 'Jakarta',
      username: 'Jakarta',
      type: 'komunitas',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_grizzly.png",
    ),
    LeaderboardItem(
      id: '87',
      name: 'Tenis Club Bandung',
      points: 290,
      rank: 1,
      location: 'Bandung',
      username: 'Bandung',
      type: 'komunitas',
      category: 'Tenis',
      season: 'Current Season',
    ),
    LeaderboardItem(
      id: '88',
      name: 'Ufo Enthusiast',
      points: 230,
      rank: 2,
      location: 'Bandung',
      username: 'Bandung',
      type: 'komunitas',
      category: 'Tenis',
      season: 'Current Season',
    ),
    LeaderboardItem(
      id: '89',
      name: 'Le Tropico',
      points: 200,
      rank: 3,
      location: 'Bandung',
      username: 'Bandung',
      type: 'komunitas',
      category: 'Tenis',
      season: 'Current Season',
    ),
    LeaderboardItem(
      id: '90',
      name: 'For East United',
      points: 100,
      rank: 5,
      location: 'Surabaya',
      username: 'Surabaya',
      type: 'komunitas',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_avatar.png",
      isUser: true,
    ),
    LeaderboardItem(
      id: '91',
      name: 'Kawan Ayo United',
      points: 190,
      rank: 4,
      location: 'Jakarta',
      username: 'Jakarta',
      type: 'komunitas',
      category: 'Badminton',
      season: 'Current Season',
      imageUrl: "assets/icons/ic_kawan_ayo.png",
      isUser: true,
    ),
  ];

  // Data untuk Participated
  static List<LeaderboardItem> get participatedLeaderboard => [
    LeaderboardItem(
      id: '83',
      name: 'Budiman Tanuwijaya',
      username: '@budimantanu',
      points: 105,
      rank: 456,
      location: 'Surabaya',
      type: 'participated',
      category: 'Tenis Meja',
      season: 'Current Season',
      isUser: true,
      imageUrl: "assets/icons/ic_budiman.png",
    ),
  ];

  // Filter options tetap sama...
  static List<FilterOption> get periodeOptions => [
    FilterOption(
      id: 'all_time',
      name: 'All Time',
      type: 'periode',
      isSelected: true,
    ),
    FilterOption(
      id: 'jan_mar_2024',
      name: 'Januari - Maret 2024',
      type: 'periode',
    ),
    FilterOption(id: 'current_season', name: 'Current Season', type: 'periode'),
    FilterOption(
      id: 'oct_dec_2023',
      name: 'Oktober - Desember 2023',
      type: 'periode',
    ),
    FilterOption(
      id: 'jul_aug_2023',
      name: 'Juli - Agustus 2023',
      type: 'periode',
    ),
  ];

  static List<SportCategory> get sportCategories => [
    SportCategory(
      id: '1',
      name: 'Badminton',
      emoji: 'assets/icons/ic_badminton.png',
      isPreferred: true,
    ),
    SportCategory(
      id: '2',
      name: 'Squash',
      emoji: 'assets/icons/ic_squash.png',
      isPreferred: true,
    ),
    SportCategory(
      id: '3',
      name: 'Padel',
      emoji: 'assets/icons/ic_padel.png',
      isPreferred: true,
    ),
    SportCategory(
      id: '4',
      name: 'Mini Soccer',
      emoji: 'assets/icons/ic_futsal.png',
      isPreferred: true,
    ),
    SportCategory(
      id: '5',
      name: 'Tenis Meja',
      emoji: 'assets/icons/ic_tenis_meja.png',
    ),
    SportCategory(id: '6', name: 'Tenis', emoji: 'assets/icons/ic_tennis.png'),
    SportCategory(
      id: '7',
      name: 'Pickleball',
      emoji: 'assets/icons/ic_pickleball.png',
    ),
  ];

  static List<Region> get regions => [
    Region(
      id: 'jakarta',
      name: 'Jakarta',
      code: 'DKI Jakarta',
      isPopular: true,
    ),
    Region(
      id: 'tangerang',
      name: 'Tangerang',
      code: 'Tangerang',
      isPopular: true,
    ),
    Region(id: 'bekasi', name: 'Bekasi', code: 'Bekasi', isPopular: true),
    Region(id: 'bogor', name: 'Bogor', code: 'Bogor', isPopular: true),
    Region(id: 'depok', name: 'Depok', code: 'Depok', isPopular: true),
    Region(id: 'bandung', name: 'Bandung', code: 'Bandung', isPopular: true),
    Region(
      id: 'yogyakarta',
      name: 'Yogyakarta',
      code: 'Yogyakarta',
      isPopular: true,
    ),
    Region(id: 'surabaya', name: 'Surabaya', code: 'Surabaya', isPopular: true),
    Region(id: 'malang', name: 'Malang', code: 'Malang', isPopular: true),
  ];

  static List<FilterOption> get kategoriOptions => [
    FilterOption(id: '1', name: 'Tunggal', type: 'kategori'),
    FilterOption(id: '2', name: 'Ganda', type: 'kategori'),
    FilterOption(
      id: '3',
      name: 'Komunitas',
      type: 'kategori',
      isSelected: true,
    ),
  ];

  static List<FilterOption> get locationOptions => [
    FilterOption(id: '1', name: 'Surabaya', type: 'location'),
    FilterOption(id: '2', name: 'Jakarta', type: 'location'),
    FilterOption(id: '3', name: 'Bandung', type: 'location'),
    FilterOption(id: '4', name: 'Yogyakarta', type: 'location'),
    FilterOption(id: '5', name: 'Bali', type: 'location'),
    FilterOption(id: '6', name: 'Semarang', type: 'location'),
    FilterOption(id: '7', name: 'Malang', type: 'location'),
    FilterOption(id: '8', name: 'Medan', type: 'location'),
  ];
}
